# Generated by Django 4.2.20 on 2025-03-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expect_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('jobdesc', models.TextField(blank=True, null=True)),
                ('jobclient', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('userpic', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobdelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobdelegationdate', models.DateField(auto_now_add=True)),
                ('jobassign', models.ManyToManyField(null=True, related_name='assigned_recruiters', to='crud.recruiter')),
                ('jobid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='crud.job')),
            ],
        ),
    ]
