# Generated by Django 4.2.20 on 2025-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdelegation',
            name='jobassign',
            field=models.ManyToManyField(blank=True, related_name='assigned_recruiters', to='crud.recruiter'),
        ),
    ]
